apiVersion: v1
kind: Secret
metadata:
  name: toggle-master-secret
  namespace: toggle-master
type: Opaque
stringData:
  auth-db-user: auth_user
  auth-db-pass: auth_pass
  auth-db-name: auth_db
  auth-db-url: postgres://auth_user:auth_pass@postgres-auth:5432/auth_db?sslmode=disable
  flags-db-user: flags_user
  flags-db-pass: flags_pass
  flags-db-name: flags_db
  flags-db-url: postgres://flags_user:flags_pass@postgres-flags:5432/flags_db
  targeting-db-user: targeting_user
  targeting-db-pass: targeting_pass
  targeting-db-name: targeting_db
  targeting-db-url: postgres://targeting_user:targeting_pass@postgres-targeting:5432/targeting_db
  master-key: local-master-key
  service-api-key: GERAR_APOS_DEPLOY_AUTH_SERVICE
  aws-access-key-id: AKIAIOSFODNN7EXAMPLE
  aws-secret-access-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
