apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: toggle-master-ingress
  namespace: toggle-master
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: auth.togglemaster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8001
    - host: flags.togglemaster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flag-service
                port:
                  number: 8002
    - host: targeting.togglemaster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: targeting-service
                port:
                  number: 8003
    - host: evaluation.togglemaster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evaluation-service
                port:
                  number: 8004
