apiVersion: v1
kind: Secret
metadata:
  name: toggle-master-secret
  namespace: toggle-master
type: Opaque
stringData:
  auth-db-user: auth_user
  auth-db-pass: auth_pass
  auth-db-name: postgres
  auth-db-url: postgresql://auth_user:auth_pass@togglemaster-auth.xxxxxxxxxxxx.us-east-1.rds.amazonaws.com:5432/postgres
  flags-db-user: flags_user
  flags-db-pass: flags_pass
  flags-db-name: flags_db
  flags-db-url: postgresql://flags_user:flags_pass@togglemaster-flags.xxxxxxxxxxxx.us-east-1.rds.amazonaws.com:5432/flags_db
  targeting-db-user: targeting_user
  targeting-db-pass: targeting_pass
  targeting-db-name: targeting_db
  targeting-db-url: postgresql://targeting_user:targeting_pass@togglemaster-targeting.xxxxxxxxxxxx.us-east-1.rds.amazonaws.com:5432/targeting_db
  master-key: local-master-key
  service-api-key: GERAR_APOS_DEPLOY_AUTH_SERVICE
